services:
  - type: web
    name: meva-garden
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
